### ISSUE TITLE
2.0.3 table inheritance problem

### ISSUE THREAD

**Issue by alepore** [rubysherpas/paranoia#190] opened 2014-12-06 13:39 UTC
Hi, i have a Postgresql Rails (Spree) app with:

``` ruby
class Price < ActiveRecord::Base
  acts_as_paranoid
  ...

class FlashSalePrice < Price
  self.table_name = 'spree_flash_sale_prices'
 ...
```

Using paranoia `2.0.3` i see invalid queries like:

``` sql
SELECT "spree_flash_sale_prices".* FROM "spree_flash_sale_prices" WHERE "spree_prices"."deleted_at" IS NULL ...
```

so paranoia it's using the parent class table name. error:

`PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "spree_prices"`

With paranoia `2.0.2` it's fine:

``` sql
SELECT "spree_flash_sale_prices".* FROM "spree_flash_sale_prices" WHERE "spree_flash_sale_prices"."deleted_at" IS NULL ...
```

I've taken a look but i'm not sure which 2.0.3 commit introduced this, ideas?

Thanks!!

**Comment by johnnymo87** [comment] 2014-12-12 19:38
@alepore I walked through the commits from 2.0.2 to 2.0.3, and [this commit](https://github.com/radar/paranoia/commit/55adceeef96fefc23e2bc9fed75f8917635ec642) is where it broke for me.

**Comment by danivovich** [comment] 2014-12-14 04:31
I'm having a related issue with the same commit as the breaking commit.  I suspect my issue is when a relation is joined in the join table name is not correct since its using the table_name value from the default scope, not the alias from the join.  I'll see if I can put together a specific and isolated example tomorrow.

**Comment by TrevorHinesley** [comment] 2015-02-02 20:56
+1, need this resolved.

**Comment by radar** [comment] 2015-02-02 21:07
+1 comments are not useful at all. There isn't some magical tipping point where we go "wow, it's crossed 25 +1s!! I better stop what I'm doing and work on this issue right now!". There is no service contract.

I mean, what do you hope to achieve by posting that? That we will somehow be inspired to work on this issue? This is not how open source works.

Open source works by us providing you with code that is fit for a particular purpose and doesn't guarantee at all that it will work for your particular purpose. (See: the LICENSE file)

 OSS works also when people outside of the core team are willing to dedicate some time to investigating and fixing the issues they encounter. Some good examples of this are found in Rails. 

Could you please spend some time investigating the cause of this issue, even if it is just providing us with an app which reproduces the problem concisely?

Or if you're willing to sponsor my time to investigate this issue I'm sure I can find some spare time somewhere to see if it can be fixed.

Thanks.

**Comment by TrevorHinesley** [comment] 2015-02-02 21:09
@radar honestly, that was rude and uncalled for. I dedicate time to open source projects ALL the time, and have gems of my own. I simply stated I needed it resolved for my project, which was true. I believe the point of +1 is to show that a fix has a widespread need (there has to be priority among bug fixes, as I'm sure you're aware). I am working on a solution at the moment myself (as you can see, I've forked this). Thanks for the gem, good stuff.

**Comment by TrevorHinesley** [comment] 2015-02-02 22:04
As @johnnymo87 pointed out, it's indeed these two lines.

32: `with_deleted.where.not(table_name => { paranoia_column => paranoia_sentinel_value} )`

185: `default_scope { where(table_name => { paranoia_column => paranoia_sentinel_value }) }`

I've tried a couple things, but without knowing the current aliases being used in the query, I'm not sure there's a way to replace `table_name` properly. Open to suggestions.

**Comment by stgeneral** [comment] 2015-02-15 10:17
Looks the same for my case. The breaking changes seems were introduced to fix #102 by #164.
Here is a pull request with fixes that work for me - #212.

@alepore what rails version do you use? Can you test your case against rails 4.0 and 4.1?

**Comment by TrevorHinesley** [comment] 2015-04-26 16:53
#212 was merged in which will fix this, @radar do you happen to know when the next gem version will be published? Using rails4 branch right now. Thanks for merging that in!

**Comment by radar** [comment] 2015-04-28 02:55
2.1.2 has been released.

**Closed as completed** 2015-05-23 12:04 UTC
