### ISSUE TITLE
Update repo's description

### ISSUE THREAD

**Issue by anmolarora** [rubysherpas/paranoia#445] opened 2018-06-03 14:32 UTC
README file says it works for Rails 5 but the description says it works only for Rails 3 & 4

**Comment by BenMorganIO** [comment] 2018-06-03 20:52
Cannot happen as no active contributor has enough access to change the description. Or at least, I cannot.

**Comment by anmolarora** [comment] 2018-06-04 04:10
Is that so?!
I would like to keep it open with the hope someone might change it in future.

**Comment by Br3nda** [comment] 2018-07-18 03:58
duplicate of https://github.com/rubysherpas/paranoia/issues/420

**Comment by sevenseacat** [comment] 2018-07-18 04:06
Fixed :)

**Closed as completed by sevenseacat** 2018-07-18 04:06 UTC
