### ISSUE TITLE
Calling `destroy!` twice really destroys records?!

### ISSUE THREAD

**Issue by pcreux** [rubysherpas/paranoia#201] opened 2015-01-13 00:40 UTC
I was not expecting the method `destroy!` to really destroy a soft-deleted record. That's making me even more paranoid! :smile_cat: 

In my opinion, `destroy!` should have a consistent behaviour:
- `destroy` **soft** destroys a record and **return false** on failure
- `destroy!` **soft** destroys a record and **raises an exception** on failure
- `really_destroy` **really** destroys a record and **return false** on failure
- `really_destroy!` **really** destroys a record and **raises an exception** on failure

**Comment by jhawthorn** [comment] 2015-01-19 22:44
Hmm. You're right, I don't think this is intended behaviour.

Here's the offending code:

https://github.com/radar/paranoia/blob/rails4/lib/paranoia.rb#L72-L76

We should try to fix this in the next release

**Comment by jhawthorn** [comment] 2015-01-22 22:53
Thanks for the report. This is fixed in the current `rails4` branch and in `2.1.0.pre` 

See test added in 356b1357041943f21e1bb7c1ddeb2afcc1d32fee

**Closed as completed by jhawthorn** 2015-01-22 22:53 UTC

**Comment by pcreux** [comment] 2015-01-22 23:24
Awesome thanks!
